### ISSUE TITLE
Use a dummy value instead of an actual API key in source

### ISSUE THREAD

**Issue by randomdross** [quickshiftin/postmates-client#12]
Though this key is being disabled, it should be replaced by a dummy value in source:
https://github.com/quickshiftin/postmates-client/blob/master/tests/ClientTest.php#L7

**Comment by quickshiftin** [comment]
This has been replaced. Apologies for the hassle!

https://github.com/quickshiftin/postmates-client/blob/master/tests/ClientTest.php
