### ISSUE TITLE
Feature request: Error Logging

### ISSUE THREAD

**Issue by nquamdbridge** [quickshiftin/postmates-client#2]
It would be great if there was an error logging feature or general request log. I don't actually know if there is a failed order and I'm probably going to write something to make this work for my solution but it would be a great addition to just turn it on or off in the request configuration.

**Comment by quickshiftin** [comment]
I don't consider a feature request an issue. Other folks have contributed; if you want to implement some logging component I'm sure others would really appreciate it. Just shoot me a Pull Request and I'll get it merged in!
