### ISSUE TITLE
v1.2 is broken

### ISSUE THREAD

**Issue by aditya-cherukuri** [quickshiftin/postmates-client#9]
I believe the new version is broken. The tests are failing and I think there is something wrong with this code snippet in Client.php

private function _request($type, $endpoint, $params = [])
    {
        try {
            $oRsp = $this->send($oRq);
            return Factory::create($oRsp->json());
        } catch(\GuzzleHttp\Exception\RequestException $e) {
            $this->addException($e);
        } catch(\Exception $e) {
            $this->addException($e);
        }
    }

As you can see we are doing a send($oRq) and $oRq has not been declared or passed via arguments. The arguments that are passed are also not used.

**Comment by quickshiftin** [comment]
It must have been broken by / during the integration of the guzzle 6 pull
request last week. I'll have a look tonight and try to get it fixed asap.

On Mon, Mar 20, 2017 at 11:15 AM, aditya-cherukuri <notifications@github.com

**Comment by quickshiftin** [comment]
Thank you for the pull request, I've merged it in and created the v1.3 tag.
